### PR TITLE
Generalise over choice of field

### PR DESCRIPTION
**Pull request by gdijkstra**

### CODE REVIEW

**Comment by sdiehl** [comment]
This pulls in lens as a dependency. Let's not do that.

**Comment by gdijkstra** [comment]
Is that a problem in terms of build times?

**Comment by gdijkstra** [comment]
This PR has been subsumed by https://github.com/adjoint-io/bulletproofs/pull/7, so I'm closing this one

**Comment by gdijkstra** [comment]
Reopen by Alberto's request

**Comment by sdiehl** [comment]
With these changes this looks like it's sensible to merge now.

**Comment by gdijkstra** [comment]
:+1: It's ready to merge

**Pull request merged**
